### ISSUE TITLE
SIGMA rule translation -> lucene query replaces spaces " "  with "_ws_" which lucene doesnt understand.

### ISSUE THREAD

**Issue by tallyoh** [opensearch-project/security-analytics#1024]
**What is the bug?**
A sigma rules with a whitespace gets incorrectly translated to a search query with "_ws_" instead of a whitespace.

**How can one reproduce the bug?**
detection:
  condition: (selection and selection_evt) and not filter_main_known_locations
  filter_main_known_locations:
    process.executable|contains:
    - C:\\Program Files (x86)\\Windows Defender\\
    - C:\\Program Files\\Microsoft Security Client\\
    - C:\\Program Files\\Windows Defender\\
    - C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\
    - C:\\Windows\\WinSxS\\
  selection:
    process.name:
    - MpCmdRun.exe
    - NisSrv.exe
  selection_evt:
    event.code: 1
    event.module: sysmon

**Results in:**
	(((process.name: "MpCmdRun.exe") OR (process.name: "NisSrv.exe")) AND ((event.code: 1) AND (event.module: "sysmon"))) AND ((((NOT process.executable: *C\:\\Program_ws_Files_ws_\(x86\)\\Windows_ws_Defender\\* AND _exists_: process.executable) AND (NOT process.executable: *C\:\\Program_ws_Files\\Microsoft_ws_Security_ws_Client\\* AND _exists_: process.executable) AND (NOT process.executable: *C\:\\Program_ws_Files\\Windows_ws_Defender\\* AND _exists_: process.executable) AND (NOT process.executable: *C\:\\ProgramData\\Microsoft\\Windows_ws_Defender\\Platform\\* AND _exists_: process.executable) AND (NOT process.executable: *C\:\\Windows\\WinSxS\\* AND _exists_: process.executable))))

**What is the expected behavior?**
A whitespace should work properly in a sigma rule that is translated to a lucene query

**What is your host/environment?**
OS 2.13

**Do you have any additional context?**
Looking in github, I can see where the "_ws_" is being set. Not sure why.
https://github.com/search?q=repo%3Aopensearch-project%2Fsecurity-analytics%20%20_ws_&type=code

**Comment by tallyoh** [comment]
Just wondering if there has been any movement on this and if a fix is coming in 2.15.  Thanks!

**Comment by ELKHostmaster** [comment]
@sbcd90  - good afternoon. Do you have any suggestion how I could get some attention to this bug? I wish I were a developer, but I'm unable to contribute a fix myself. I welcome any suggestions. Thank you.

**Comment by ELKHostmaster** [comment]
@praveensameneni  Hi Praveen, this bug has been opened for a long time. Do you have any suggestion how I can get some attention to it? I'm not a developer, but can I buy someone a pizza?

**Comment by sbcd90** [comment]
hi @ELKHostmaster , will work on it for next release.

**Comment by givilleneuve** [comment]
Hi everyone,

Just seeing out there if someone found an alternative for now?

Thank you,

**Comment by givilleneuve** [comment]
Hi @sbcd90 , do you know if it should have it available in the 2.19 since looks like the 2.18 the bug is still there?

Thank you very much,

**Comment by tallyoh** [comment]
Will this be fixed in 2.19?  It feels like the Security Analytics module is not getting the attention it deserves. Lots of untriaged and open issues. Little to no feedback in github, and slack channels. Will this module be supported long-term?

**Comment by rios0rios0** [comment]
https://github.com/opensearch-project/security-analytics/pull/1458/files

**Comment by tallyoh** [comment]
@sbcd90   good morning. Will this patch make it into the 2.19 release? This is a really bad bug that has plagued us for the better part of a year now.

@rios0rios0  thank you again for supporting this fix!

**Comment by improvisec** [comment]
I can confirm this issue is still present in OpenSearch 3.2.0.

I reproduced it using prepackaged Windows Security Analytics rules and confirmed that the literal `_ws_` token changes query results and causes false-positive findings.

## Environment

- OpenSearch: 3.2.0
- Security Analytics plugin: bundled with OpenSearch 3.2.0
- Detector type: `windows`
- Detector index: alias pointing to Windows event indices
- Rules: prepackaged Security Analytics rules

## Example 1: Unauthorized System Time Modification

Rule ID:

    faa031b5-21ed-4e02-8881-2591f98d82ed

Rule name:

    Unauthorized System Time Modification

The relevant Sigma rule logic is:

    detection:
      selection:
        EventID: 4616
      filter1:
        ProcessName:
          - C:\Program Files\VMware\VMware Tools\vmtoolsd.exe
          - C:\Windows\System32\VBoxService.exe
          - C:\Windows\System32\oobe\msoobe.exe
      filter2:
        ProcessName: C:\Windows\System32\svchost.exe
        SubjectUserSid: S-1-5-19
      condition: selection and not 1 of filter*

The matching event contains:

    EventID: 4616
    ProcessName: C:\Program Files\VMware\VMware Tools\vmtoolsd.exe
    SubjectUserSid: S-1-5-18

This event should be excluded by `filter1`.

However, the query stored in the Security Analytics finding contains:

    NOT winlog.event_data.ProcessName:
    "C\:\\Program_ws_Files\\VMware\\VMware_ws_Tools\\vmtoolsd.exe"

The original value:

    C:\Program Files\VMware\VMware Tools\vmtoolsd.exe

was changed to:

    C:\Program_ws_Files\VMware\VMware_ws_Tools\vmtoolsd.exe

Since the indexed value contains real spaces, the exclusion does not match and the event incorrectly produces a finding.

I verified that the Security Analytics field mappings and aliases resolve correctly:

    winlog.event_id
    -> Event.System.EventID

    winlog.event_data.ProcessName
    -> Event.EventData.ProcessName

    winlog.event_data.SubjectUserSid
    -> Event.EventData.SubjectUserSid

Retrieving the document through those aliases returns the expected values:

    winlog.event_id:
      4616

    winlog.event_data.ProcessName:
      C:\Program Files\VMware\VMware Tools\vmtoolsd.exe

    winlog.event_data.SubjectUserSid:
      S-1-5-18

A manually constructed equivalent OpenSearch Query DSL query using the correct path value excludes the event successfully.

This indicates that the problem is in Security Analytics rule compilation rather than field mapping or alias resolution.

## Example 2: Pass the Hash Activity 2

Rule ID:

    8eef149c-bd26-49f2-9e5a-9b00e3af499b

Rule name:

    Pass the Hash Activity 2

The rule excludes events where:

    TargetUserName = "ANONYMOUS LOGON"

The compiled finding query contains:

    NOT winlog.event_data.TargetUserName: "ANONYMOUS_ws_LOGON"

instead of:

    NOT winlog.event_data.TargetUserName: "ANONYMOUS LOGON"

The complete relevant compiled query was:

    (((winlog.event_id: 4624)
      AND (winlog.event_data.SubjectUserSid: "S\-1\-0\-0")
      AND (winlog.event_data.LogonType: "3")
      AND (winlog.event_data.LogonProcessName: "NtLmSsp")
      AND (winlog.event_data.KeyLength: "0"))
     OR
     ((winlog.event_id: 4624)
      AND (winlog.event_data.LogonType: "9")
      AND (winlog.event_data.LogonProcessName: "seclogo")))
    AND
    ((NOT winlog.event_data.TargetUserName: "ANONYMOUS_ws_LOGON"
      AND _exists_: winlog.event_data.TargetUserName))

I executed the exact compiled query from the finding:

    31 matches

I then replaced `_ws_` with an actual space and executed the otherwise identical query:

    6 matches

This means 25 additional matches were caused by the whitespace substitution in this dataset.

## Scope observed

I scanned the compiled queries from the detector findings for `_ws_`.

Two affected prepackaged rules were identified:

    8eef149c-bd26-49f2-9e5a-9b00e3af499b
    Pass the Hash Activity 2

    faa031b5-21ed-4e02-8881-2591f98d82ed
    Unauthorized System Time Modification

This confirms that the issue is not cosmetic. `_ws_` changes query semantics and can cause substantial false-positive inflation, particularly in negative filters.

For the `Pass the Hash Activity 2` example:

    Compiled query:            31 matches
    Query with spaces fixed:    6 matches
    Additional false matches:  25

That is approximately 81% false-positive inflation in this test dataset.

## Related Wazuh issue and fix

Wazuh reproduced the same underlying problem in its Security Analytics fork:

- wazuh/wazuh-indexer-security-analytics#127
- Fixed by wazuh/wazuh-indexer-security-analytics#162

Their fix replaces the internal `_ws_` placeholder with escaped whitespace in the generated Lucene query.

Their validation shows a `contains` condition compiling to a query such as:

    message: *one\ two*

rather than retaining `_ws_`.

My OpenSearch 3.2.0 reproduction shows that the same underlying issue also affects exact quoted values in exclusion filters, not only `contains` modifiers.

Examples:

    "ANONYMOUS LOGON"
    -> "ANONYMOUS_ws_LOGON"

and:

    C:\Program Files\VMware\VMware Tools\vmtoolsd.exe
    -> C:\Program_ws_Files\VMware\VMware_ws_Tools\vmtoolsd.exe

This causes negative filters to fail and produces false-positive findings.

It may be useful to review or port the corresponding Wazuh change into the upstream OpenSearch Security Analytics repository, while ensuring that the fix applies to:

- exact string matches;
- exclusion filters;
- quoted values;
- Windows paths containing spaces;
- wildcard modifiers;
- `contains`;
- `startswith`;
- `endswith`;
- positive and negative comparisons.

## Expected behavior

Spaces inside Sigma string values should be preserved in the final Lucene query using appropriate escaping.

For example:

    "C\:\\Program Files\\VMware\\VMware Tools\\vmtoolsd.exe"

and:

    "ANONYMOUS LOGON"

## Actual behavior

Spaces are replaced with the literal token `_ws_`:

    "C\:\\Program_ws_Files\\VMware\\VMware_ws_Tools\\vmtoolsd.exe"

and:

    "ANONYMOUS_ws_LOGON"

This changes query semantics and causes false-positive findings.

Please let me know if additional detector, finding, field-mapping, event, or query output would help.
